{{- if .Values.ollama.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portkey-gateway.fullname" . }}-ollama
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portkey-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "portkey-gateway.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
{{- end }}

